[package]
name = "dc-common"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
mime = "0.3.17"
once_cell = "1.19.0"
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_with = "3.4.0"
serde_yaml = "0.9.27"
thiserror = "1.0.51"
